image: ubuntu

stages:
  - deploy

deploy_smalink:
  environment: production
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh mindsers@51.255.163.174 -p 6421 'rm -rf /var/www/nath/* /var/www/nath/.git*'
    - ssh mindsers@51.255.163.174 -p 6421 'git clone git@git.nathanaelcherrier.com:nath-com/home-nath.git /var/www/nath'
    - ssh mindsers@51.255.163.174 -p 6421 'chmod -R 775 /var/www/nath/*'
    - ssh mindsers@51.255.163.174 -p 6421 'chown :www-data -R /var/www/nath/*'
  only:
    - master
  tags:
    - docker
