name: CI

on:
  push:
    branches:
      - develop
      - feature/*
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install --purelock-file
    - name: Test
      run: yarn test --sourceMap=false --browsers=ChromeHeadless --watch=false
      env:
        CI: true

  build:
    runs-on: ubuntu-latest
    needs: [test]
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install --purelock-file
    - name: Build
      run: yarn build
      env:
        CI: true
